---
title: "tt-01.18.2022"
author: "Travis VanNoy"
date: "1/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load library}
library(tidytuesdayR)
library(tidyverse)
library(skimr)
```

```{r load data} 

tuesdata <- tidytuesdayR::tt_load('2022-01-18')

chocolate <- tuesdata$chocolate
```


```{r explore data}

chocolate %>% skim() %>% view()

chocolate %>% 
  group_by(rating) %>% 
  count() %>% 
  arrange(desc(rating))

chocolate %>% 
  slice_max(rating, n = 1) %>%
  group_by(company_manufacturer) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  view()

chocolate %>% 
  slice_max(rating, n = 1) %>% 
  group_by(country_of_bean_origin) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  view()

chocolate %>% 
  slice_max(rating, n = 1) %>% 
  group_by(company_manufacturer,
           country_of_bean_origin) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  view()
```


```{r results result}

chocolate %>% 
  slice_max(rating, n = 1) %>% 
  group_by(company_manufacturer,
           country_of_bean_origin) %>% 
  ggplot(aes(country_of_bean_origin)) +
  geom_bar(aes(fill = country_of_bean_origin
               ),
           show.legend = FALSE) +
  coord_flip()
  

```


